### PR TITLE
Sensor Fusion Module

### PR DESCRIPTION
**Pull request by m-georgi**
Add Sensor Fusion Module 
  - implement module in modules/sensorfusion.py
  - include relevant constant in modules/__init__.py and
    modules/base.py
  - add sensorfusion as attribute to MetaWearClient and
    initialize on startup

￼Add Sensor Fusion usage example

### CODE REVIEW

**Comment by m-georgi** [comment]
Sensor Fusion is working, but unfortunately limiting the data rate using time data processors is resulting in strange data.
I filed a bug report (http://community.mbientlab.com/discussion/1960/incorrect-data-when-using-time-data-processor-on-sensor-fusion-signals), but will leave the commits in the pull request.

**Comment by hbldh** [comment]
Looks good! I will try to update metaWear cpp API to version 0.7.10 that addresses your issue and merge this PR soon.

**Comment by hbldh** [comment]
Merged this to version 0.7.1.

**Comment by hbldh** [comment]
Thank you very much for this! A necessary addition of features.

**Pull request closed without merging**
